# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 51))
        self.groupBox.setObjectName("groupBox")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(10, 20, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(340, 20, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 201, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 651, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 631, 531))
        self.treeWidget.setObjectName("treeWidget")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidget_2.setGeometry(QtCore.QRect(10, 10, 631, 531))
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.tab_3)
        self.treeWidget_3.setGeometry(QtCore.QRect(10, 10, 631, 531))
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Поиск"))
        self.pushButton.setText(_translate("MainWindow", "Найти"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Земли сельзоз назначения"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Земли промышленности"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Земли населенных пунктов"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Кадастровый номер"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Описание перечня"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Дата возникновения основания для определения кадастровой стоимости"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Земли сельзоз назначения"))
        self.treeWidget_2.headerItem().setText(0, _translate("MainWindow", "Кадастровый номер"))
        self.treeWidget_2.headerItem().setText(1, _translate("MainWindow", "Описание перечня"))
        self.treeWidget_2.headerItem().setText(2, _translate("MainWindow", "Дата возникновения основания для определения кадастровой стоимости"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Земли промышленности"))
        self.treeWidget_3.headerItem().setText(0, _translate("MainWindow", "Кадастровый номер"))
        self.treeWidget_3.headerItem().setText(1, _translate("MainWindow", "Описание перечня"))
        self.treeWidget_3.headerItem().setText(2, _translate("MainWindow", "Дата возникновения основания для определения кадастровой стоимости"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Земли населенных пунктов"))
